apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-bedrock-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-bedrock-app
  template:
    metadata:
      labels:
        app: go-bedrock-app
    spec:
      serviceAccountName: go-bedrock-app-sa
      containers:
      - name: go-bedrock-app
        image: 663864911215.dkr.ecr.us-west-2.amazonaws.com/go-bedrock-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-bedrock-app-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::663864911215:role/amazon-q-cli-operation-Bedrock-App-Role
---
apiVersion: v1
kind: Service
metadata:
  name: go-bedrock-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: go-bedrock-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
